export const siteRoutes = [
  '/',
  '/products',
  '/products/smart-collar',
  '/products/app',
  '/products/health-platform',
  '/solutions',
  '/solutions/family',
  '/solutions/hospital',
  '/solutions/store',
  '/about',
  '/partners',
  '/cases',
  '/news',
  '/contact',
  '/demo',
  '/privacy',
  '/terms',
] as const
